### ISSUE TITLE
PDF displaying failure at long city names

### ISSUE THREAD

**Issue by benhartwich** [rmbinder/FormFiller#59]
Hi,

great plugin! We´ve identified a problem: when having long city names the pdf label export has a failure. The names are displayed into the next label instead of displaying it partly into a new line. Is there any chance to solve this problem anyhow? I am using the template "Adressettiketten". Is there a way to insert an own template?

Regards
![2022-05-11_09h18_19](https://user-images.githubusercontent.com/4061954/167791859-bba055d0-011a-4dd7-b119-ba8b7abc27e3.png)

**Comment by rmbinder** [comment]
> Is there any chance to solve this problem anyhow?

The problem is that at the time the data is written to the PDF page, I can't read the length of the text.
It might be possible to add something in the settings like: "Line break after x characters". I'll take a look.

> Is there a way to insert an own template?

First export a configuration (e.g. "Adressetiketten"), then import it again. Now there is an additional configuration "Adressetiketten - Copy". This can now be customized like larger labels, smaller font...

**Comment by rmbinder** [comment]
With the parameters WL and WW it is now possible to split a record or an address specification into its individual words. 

Example: WL=15;WW=5 means that the original sentence is split into individual sentences with a maximum of 15 characters. The individual sets are printed one below the other with a spacing of 5 mm.

Neuhofen a.d. Krems
will be
Neuhofen a.d.
Krems
